feat(purge): purge outer URLs with and without html
adobe/helix-purge pull request #13
Opened 2020-09-02 16:31 UTC by rofe

Fix #12 

@trieloff I also noticed that the inner CDN ended up getting double purged using `outerPurge()` if present in `xfh`. Assuming this was unintentional, I added a check to skip URLs with the inner host and not use `outerPurge()` on it again. Please double-check and let me know if I misunderstood that.

2020-09-02 16:34 UTC, trieloff approved these changes

2020-09-03 01:21 UTC, tripodsan requested changes

2020-09-03 01:21 UTC, tripodsan commented on src/index.js
> +  }
and what's about the other way around?

2020-09-03 06:07 UTC, rofe commented on src/index.js
> +  }
Good point!

2020-09-03 10:45 UTC, trieloff approved these changes

2020-09-03 11:27 UTC, merged

2020-09-03 11:30 UTC, trieloff commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- `v1.2.0`
- [GitHub release](https://github.com/adobe/helix-purge/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: